pocketsvg/PocketSVG

BezierCurve4.svg
PocketSVG.m

- added non-ARC compatibility
- used -[NSBundle bundleForClass:] instead of -[NSBundle mainBundle] so that SVG files can be found when running inside Interface Builder
- fixed parsing of numbers represented in scientific notation (e.g.. 1.234e-8). I also added and SVG file that contains coords in scientific notation.

Non-ARC compatibility, Interface Builder designables compatibility, scientific notation no longer borks parsing

---

PocketSVG.h
PocketSVG.m

Adds support for:
- Quadratic Bézier (Q,q)
- Smooth quadratic Bézier (T,t)
SVG 1.1: [Quadratic Bezier Commands](http://www.w3.org/TR/SVG/paths.html#PathDataQuadraticBezierCommand)
*Note:* NSBezierPath doesn't support adding quadratic curves. The approximation using the cubic bezier function should be very accurate unless the path is scaled extremely large.

Support Quadratic Bézier paths

---

PocketSVG.m

Not considering tab (U+0009) as whitespace was causing parsing errors in valid SVG files.

Skip all characters in whitespace character set (rather than just space characters) when parsing paths

---

PocketSVG.xcodeproj/project.pbxproj
SVGBezierPath.h
SVGImageView.h
SVGImageView.m
SVGImageView_Mac.h
SVGImageView_iOS.h
SVGLayer.m
SVGPortability.h

* `SVGImageView_iOS.h`, `SVGImageView_Mac.h` and `SVGImageView.h` are doing what should be the job of just one file, so i merged them into `SVGImageView.h`
* The `SVGUI(kls) UI##kls` is clever, but is really not very readable. I changed it to a more verbose list of `#defines` (inspired by [Nuke](https://github.com/kean/Nuke/blob/master/Sources/Nuke.swift), as it'll be easier for users to understand what they are.

cross-platform improvements

---

PocketSVG.podspec

Because `'SVGEngine.h' file not found` error occurred during build, I've added them to podspec.

Fix 'SVGEngine.h' file not found error in v2 branch

---

Demos/Demo-iOS/Demo-iOS.xcodeproj/project.pbxproj
Demos/Demo-iOS/Demo-iOS/AppDelegate.swift
Demos/Demo-iOS/Demo-iOS/ViewController.swift
Demos/Demo-macOS/Demo-macOS.xcodeproj/project.pbxproj
Demos/Demo-macOS/Demo-macOS/AppDelegate.swift
Demos/Demo-macOS/Demo-macOS/ViewController.swift
PocketSVG.podspec
PocketSVG.xcodeproj/project.pbxproj
README.md
SVGBezierPath.h
SVGBezierPath.mm
SVGImageView.h
SVGLayer.m

* upgrades to Xcode 8
* updates demos for Swift 3
* add documentation for `SVGBezierPath.h`
* SVGBezierPaths loads only from URLs or XML strings (to be consistent with the API)
@fjolnir could you please help me clarify the following from SVGBezierPath?
* `resetCache`
* the `CGPath` property: which CGPath is it returning? 
* does `pathsFromSVGString` return an array of SVGBezierPaths?

V2 last fixes

---

SVGBezierPath.mm

Scaling was applied first, then re-applied as concatenation of each path's transform, resulting in incorrect size / position

Fixed incorrect transform

---

SVGBezierPath.mm

Use svgAttributes when generating SVGRepresentation for SVGBezierPath

---

SVGLayer.m

I was seeing some strange behaviour where setting the colours _prior_ to loading an SVG seemed to just ignore any colours that I had set, but only for non-default colours (i.e. colours created from their rgb component values, not `UIColor.redColor`).
I tracked this down to the `CGColorRef` objects not being retained by these property setters.
TBH I"m surprised that the result was just "not using the colour" rather than a crash of some description, but ¯\\_(ツ)_/¯

Retain CGColorRefs

---

Demos/Demo-iOS/Demo-iOS.xcodeproj/project.pbxproj
Demos/Sample SVG Files/Rectangle.svg
SVGEngine.mm

That's a proposal PR, apparently, it should start using  [rx](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/rx) and [ry](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/ry)  arguments of [\<rect\>](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect).
Also, there's already a  [CGPathAddRoundedRect](https://developer.apple.com/documentation/coregraphics/1411124-cgpathaddroundedrect) to generate rect instead of creating a path tag. 
Thanks for your comments in advance! 
Supposedly, it will fix https://github.com/pocketsvg/PocketSVG/issues/85
Cheers 🍻

Use CGPathAddRoundedRect to generate Rect.

---

SVGEngine.mm

Closes https://github.com/pocketsvg/PocketSVG/issues/116
This change matches Safari's interpretation of the SVGs I'm currently looking at?

Apply nested transformations in the correct order

---

SVGEngine.mm

SVG rounded rects and ellipses can supply either `rx`, `ry`, or both. Previously a missing attribute was interpreted as `0`, whereas the spec says it should be equal to the one that is supplied.
Also fixes an exception thrown in `CGPathAddRoundedRect` for rounded rects where the radius was greater than ½ the line length.

Rounded Rectangles & Ellipses Can Specify either or `rx` `ry`

---

CHANGELOG.md
PocketSVGTests/PocketSVGTests.swift
SVGEngine.mm

Fixes #128 
There was an issue with iOS 12 where previously, CGPath would collapse two consecutive move statements into one. This is no longer the case on iOS 12, so paths which start with move commands to points other than the origin ended up with incorrect bounding boxes, because we started every path with a `moveto 0, 0` in order to set up paths whose first command was not a move.
After this diff, we no longer move to 0, 0 if we don't need to. Instead, when appending each command, we check if we need to append a `moveto 0, 0` first. We need to do this check in every command parsing method except `appendMoveTo`, but I figured this approach would be more robust than trying to look at the first command and see if it was a move.
I also wrote a test which exposed the iOS 12 regression. …

Path generation: don't move to 0, 0 when not necessary

---

CHANGELOG.md
SVGEngine.mm

**Current behaviour**:
print "*** Error: Invalid number of parameters for A command"
and abort parsing SVG file
for example this svg - 
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50"><path d="M32.48,36.73c-2.22,2.64-2,5.9-2.21,9.28-.74-.14-1.33-.19-1.89-.36a17.79,17.79,0,0,1-10-7.67c-5.85-8.91-8.71-18.52-6.31-29.23.07-.3.12-.61.21-.91C13,5.2,13.28,5,16,5s5.6,0,8.4-.14a31.76,31.76,0,0,0,4.84-.64,4.22,4.22,0,0,1,3.57.53c2.49,1.92,4.26,4.37,4.1,7.67A27,27,0,0,0,38.4,23.13c.75,2,.43,2.77-1.5,3.72a13.74,13.74,0,0,1-16.42-3c-3.15-3.54-2.2-11.32,3.19-13A8.15,8.15,0,0,1,31.21,12c2,1.41,1.71,3.57,1.19,5.53s-1.33,4.11-3.88,4.43A3.54,3.54,0,0,1,25,20.61a4.29,4.29,0,0,1-.5-4.22,3.18,3.18,0,0,1,1-1.23c.89-.69,2.33-.67,2.74.06.55,1,0,1.59-.77,2.14a2.67,2.67,0,0,0-.42.52c.3.85.85.87,1.46.51 …

Added support for elliptical arc commands sequence after a single "a"

---

CHANGELOG.md
SVGBezierPath.mm
SVGLayer.m

Closes #158 by always setting a `SVGBezierPath.lineWidth` and only checking `scaleLineWidth` to determine if lines should be scaled. 
Since the `stroke-width` attribute is optional, it must not be relied upon when checking if a line should be scaled.
The default fallback value of `svgAttributes[@"stroke-width"]` is `1.0` - which is _also_ the default value of [`UIBezierPath.lineWidth`](https://developer.apple.com/documentation/uikit/uibezierpath/1624349-linewidth). So this PR shouldn't change the current behaviour and only fix the mentioned bug.

Fix line attributes. Closes #158

---

README.md

Closes #152.
Leaves `SVGLayer.shouldRasterize` on its default value (that is disabled) to allow crisply zoomable images.

Update README to mention rasterization

---

CHANGELOG.md
SVGEngine.mm

Reviewing code I saw that file "SVGColors.plist" was not being properly load on code.
This file was renamed from "Colors.plist" to "SVGColor.plist" on commit feafc5f but code used to load this file was not updated. (line 873 of `SVGEngine.mm`.

Fix named SVG Colors plist file loading.

---

CHANGELOG.md
SVGEngine.h
SVGEngine.mm

This adds a new parsing end point so clients can request single path objects parsed just from the d attribute of a path.
This is useful to clients that do their own xml parsing (because they need to handle special cases for text and groups) but want to take advantage of this libraries very fast parsing for path strings.
_Thank you for submitting a PR for PocketSVG_ 😀
* If you're fixing an issue, please briefly describe the current behaviour and the new behaviour. If you're addressing an [open issue](https://github.com/pocketsvg/PocketSVG/issues), please link to it.
* If you're introducing a new feature, please briefly describe the new behavior and provide code + sample SVGs for us to see it in action. 
Please also add that as an entry in our …

Single Path String Parsing API

---

SVGEngine.mm

Hola,
I'm simply applying what @robaho suggested in issue #150.
There's a description of the issue and steps to reproduce in there as well, basically it's meant to get rid of this spam:
```
CGPathGetCurrentPoint: no current point
CGPathGetCurrentPoint: no current point
CGPathGetCurrentPoint: no current point
CGPathGetCurrentPoint: no current point
CGPathGetCurrentPoint: no current point
```
Thanks!

fix point read from empty path

---

CHANGELOG.md
Demos/Demo-macOS/Demo-macOS/MacDemo.swift
PocketSVG.podspec
Sources/SVGBezierPath.mm
Sources/SVGEngine.mm
Sources/SVGImageView.m
Sources/SVGLayer.m
Sources/include/SVGBezierPath.h
Sources/include/SVGEngine.h
Sources/include/SVGImageView.h
Sources/include/SVGLayer.h
Tests/PocketSVGTests.swift

Based on @NeedNap's work on https://github.com/pocketsvg/PocketSVG/pull/181

support for viewBox attribute

---

Package.swift

**Issue description**:
Xcode 13 displays 4 warnings when PocketSVG is imported using SPM. These warnings are displayed because the Xcode is not able to find "Demos", "ci", "derived_data" and "PocketSVG.podspec". The issue is that these files/folders are mentioned in the exclude field of the package definition but the paths are relative to the path of the target. These files/folders are in the parent of the target source folder, so Xcode doesn't find them.
**Fix applied**:
To fix the problem I have removed the exclude field from the project description since it doesn't prevent Xcode from downloading those files/folders. 
Other could be to add the parent folder, something like:
```swift
exclude: ["../Demos", "../ci", "../derived_data", "../PocketSVG.podspec"],
```
I haven't tested it. not …

Remove Xcode 13 SPM related warnings

---

CHANGELOG.md
Sources/SVGEngine.mm
Tests/PocketSVGTests.swift

This PR fixes issue https://github.com/pocketsvg/PocketSVG/issues/204 in short: svg's path values can be described using leading zeros shortcuts to eliminate extra spaces (ex. 2 1 0 006 0). Current behaviour is ignoring these shortcuts and won't parse path correctly
Preprocess step for path definition string added to solve this issue. Preprocess replaces all matches of simple regex 
`(?<=[ ,])0\d` with `0 ` on path string. Regex translates as "separator zero + anyDigit". 
<details>
<summary>Note: this method may affect parsing performance.</summary>
// TODO: add parsing performance tests to keep track with updates :)
</details>

Support for leading zeros shortcut for path's values (#204)

---

CHANGELOG.md
Sources/SVGEngine.mm

Fix typos in the comments of the project and the CHANGELOG file. All backwards compatible

Fix typos of the project

---

.github/workflows/primary.yml
Package.swift
ci/build_demos.sh
ci/build_xcframework.sh
ci/test.sh

- Update CI for macOS 13
- update simulators
- fix xcode version
- wip
- wip

CI for macOS 13
